AllCops:
  Exclude:
    - "spec/spec_helper.rb"
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Metrics/MethodLength:
  Exclude:
    - "lib/game_info.rb"
    - "lib/controls/control.rb"
Metrics/ClassLength:
  Exclude:
    - "lib/board/board_layout.rb"
    - "lib/pieces/pawn.rb"
Style/ClassVars:
  Exclude:
    - "lib/board/universal_default_board.rb"
